# Generated by Django 4.2.20 on 2025-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='watches', to='main_app.tag'),
        ),
    ]
