# Generated by Django 4.2.20 on 2025-05-05 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watch_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='auction_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 16, 48, 26, 723666, tzinfo=datetime.timezone.utc)),
        ),
    ]
