# Generated by Django 4.2.20 on 2025-05-05 18:09

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_watch_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='auction_end_time',
            field=models.DateTimeField(default=main_app.models.default_auction_end),
        ),
        migrations.AlterField(
            model_name='watch',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
